<?xml version="1.0" ?>
<SmellBaseline>
  <ManuallySuppressedIssues></ManuallySuppressedIssues>
  <CurrentIssues>
    <ID>WildcardImport:FeedContentEntity.kt$import androidx.room.*</ID>
  </CurrentIssues>
</SmellBaseline>
