<?xml version="1.0" ?>
<SmellBaseline>
  <ManuallySuppressedIssues></ManuallySuppressedIssues>
  <CurrentIssues>
    <ID>TooGenericExceptionCaught:RemoteDataSource.kt$RemoteDataSource$e: Exception</ID>
  </CurrentIssues>
</SmellBaseline>
