<?xml version="1.0" ?>
<SmellBaseline>
  <ManuallySuppressedIssues></ManuallySuppressedIssues>
  <CurrentIssues>
    <ID>TooGenericExceptionCaught:FeedContentFetcher.kt$FeedContentFetcher$e: Exception</ID>
    <ID>TooGenericExceptionThrown:RssParser.kt$RssParser$throw RuntimeException("invalid version for rss content")</ID>
  </CurrentIssues>
</SmellBaseline>
