name: Build Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v1

      - name: Install Dependencies
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Unit Tests
        working-directory: ./source
        run: bash ./gradlew clean test

  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v1

      - name: Install Dependencies
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build APK
        working-directory: ./source
        run: bash ./gradlew clean build

      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: source/app/build/outputs/apk/**/*.apk
