name: Build Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    env:
      working-directory: source

    steps:
      - name: checkout source code
        uses: actions/checkout@v1

      - name: install dependencies
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: run unit tests
        run: bash ./gradlew clean test

  build:
    name: Build APK
    runs-on: ubuntu-latest
    env:
      working-directory: source

    steps:
      - name: checkout source code
        uses: actions/checkout@v1

      - name: install dependencies
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: build APK
        run: bash ./gradlew clean build

      - name: archive APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/**/*.apk
